const actionTypes = {
  CREATE_POST: 'CREATE_POST',
  DELETE_POST: 'DELETE_POST',
  UPDATE_POST: 'UPDATE_POST',
  GET_ALL_POSTS: 'GET_ALL_POSTS',
  POSTS_LOADING: 'POSTS_LOADING',
  CREATE_COMMENT: 'CREATE_COMMENT',
  GET_ALL_COMMENTS: 'GET_ALL_COMMENTS',
  SET_ERROR: 'SET_ERROR',
};
export default actionTypes;
